### ISSUE TITLE
Missing SetLogLevel

### ISSUE THREAD

**Issue by DevDevious** [lesismal/arpc#1]
Hello,

Just performed an update to the latest version and noticed `SetLogLevel` function has disappeared. This code no longer compiles `arpc.SetLogLevel(arpc.LogLevelError)`.

**Comment by lesismal** [comment]
> Hello,
> 
> Just performed an update to the latest version and noticed `SetLogLevel` function has disappeared. This code no longer compiles `arpc.SetLogLevel(arpc.LogLevelError)`.

Thank you for your feedback!
I move some files to subdirectorys, plz use log.SetLogLevel instead

```golang
"github.com/lesismal/arpc/log"

log.SetLogLevel(log.LogLevelError)
```

**Comment by DevDevious** [comment]
Thank you @lesismal .

**Comment by lesismal** [comment]
> Thank you @lesismal .

Welcome!

And I have supported some new features recently: middleware for routers and message-body-encoding, websocket-js client, pub/sub, router-level async response setting.
Unlike other rpc frameworks, arpc can be used for not only rpc, it is unlimited to many business types such as pushing system, IM, games, and so on.
Welcome to try it if any you like ~

**Comment by DevDevious** [comment]
@lesismal that's great news! Any plans on updating the docs as well ?

**Comment by lesismal** [comment]
> @lesismal that's great news! Any plans on updating the docs as well ?

Yes, I plan to update docs and code comments. Some of the new features already here [docs](https://github.com/lesismal/arpc#js-client)

**Comment by lesismal** [comment]
I modified the directory structure and renamed some functions and variables to make it look more concise:
```golang
import "github.com/lesismal/arpc/in/log"

log.SetLevel(log.LevelError)
```
