### ISSUE TITLE
confusing for mem malloc

### ISSUE THREAD

**Issue by wongoo** [lesismal/arpc#11]
```go

func (mp *MemPool) Malloc(size int) []byte {
	pbuf := mp.pool.Get().(*[]byte)
	if cap(*pbuf) < size {
		if cap(*pbuf)+holderSize >= size {
			*pbuf = (*pbuf)[:cap(*pbuf)]
			*pbuf = append(*pbuf, holderBuffer[:size-len(*pbuf)]...) // <--- allocation occur when exceed cap, why not just create a new buffer ?  
		} else {
			mp.pool.Put(pbuf)
			newBuf := make([]byte, size)
			pbuf = &newBuf
		}
	}

	if mp.Debug {
		mp.saveAllocStack(*pbuf)
	}

	return (*pbuf)[:size]
}
```

**Comment by lesismal** [comment]
Thank you for you feedback!

> allocation occur when exceed cap, why not just create a new buffer ?

1. If we just create a new buffer, we should reput the old into the pool, then there will be more buffers in the pool. And lots of the small buffer will be hardly reused and cause more reput and create.
2. Most of the time, append should not trigger the realloc(buffer move and copy), even if trigger the realloc, the buffer should be returned to the runtime or system, we don't need worry about it.
3. try this test: https://github.com/lesismal/nbio/blob/master/mempool/mempool_test.go#L7.
And change the code to that just creates a new buffer every time when the cap is not enough, compare the differences with the current implementation.

**Comment by lesismal** [comment]
望哥，内存池这里的实现还有疑问或者建议没？如果没有，咱关了呀 😄
