### ISSUE TITLE
extension/micro: feature request

### ISSUE THREAD

**Issue by landbed** [lesismal/arpc#13]
Thanks for your work, arpc is awesome.

1, In game scenario, sometimes a request from the frontend server must be transferred to a special server, not a random one.

ref: https://github.com/lesismal/arpc/blob/master/extension/micro/service.go#L210

2, RPCX has metadata called state which is very useful in production.

ref: https://github.com/rpcxio/rpcx-examples/blob/master/state/client/client.go#L21

Are you considering adding these above?

Thanks!

**Comment by lesismal** [comment]
为了能省事点并且说清楚，我用中文回复吧

> 1, In game scenario, sometimes a request from the frontend server must be transferred to a special server, not a random one.

arpc的设计原则是 less is more，最初的出发点之一是尽量少依赖，核心功能其实都在  主目录+codec+log+util 中，这部分核心中其实只依赖标准库、不操心第三方，所以连 codec 默认都是使用的标准库 json。为了最少依赖（代码更干净、即使嵌入式设备也可以友好使用、不依赖三方变更带来的相关升级烦恼），这部分核心没有包括 transport/codec/midleware/micro service 等各种具象化的依赖，而是放到了 extesion 中。examples 在于提供常规示例，extesions 虽然提供一些基础的扩展，但其实不算是 arpc 的核心部分，只是为了提供扩展示例。对于微服务服务发现这些而言，实现起来主要是个连接管理的策略，太简单了，比如您说的某个链接需要路由到同类服务指定节点，只需要在这里增加一点类似的支持：
```golang
// ClientBy returns a reachable client by service's name.
func (list *serviceNodeList) index(i int) (*arpc.Client, error) {
	list.mux.RLock()
	defer list.mux.RUnlock()
	l := len(list.nodes)
	if l == 0 {
		return nil, ErrServiceNotFound
	}
	return list.nodes[uint64(i)%uint64(len(list.nodes))], nil
}

func (s *serviceManager) ClientByIndex(serviceName string, i int) (*arpc.Client, error) {
	s.mux.RLock()
	defer s.mux.RUnlock()
	list, ok := s.serviceList[serviceName]
	if ok {
		return list.index(i)
	}
	return nil, ErrServiceNotFound
}
```
这是我在网页上随手编辑的，没实际跑、可能会有错误，只是简单示例。

而且对于服务注册与发现而言，其实都是配置注册发现、配置相关的一点管理功能，实现起来算是简单，服务注册发现的组件也不限于etcd、zookeeper、consul各种，甚至用数据库+轮询也可以实现。每个公司的技术架构中包含的组件不一而同，所以我不希望arpc本身需要强制用户增加技术栈从而增加技术架构和运维等一系列的复杂度和成本。所以extension中的这个服务发现的serviceManager的实现，其实也不是依赖于etcd的。希望有需要的用户，自己根据自家的喜好，来稍微定制下相关的策略即可。

> 2, RPCX has metadata called state which is very useful in production.

我还没有仔细研究过 rpcx 的这块代码，您能介绍下这个 metadata 的应用场景吗？
如果是该 client 自己持有的 metadata，arpc.Client.Set/Get 可以设置自己的数据但并不是保存在远端。如果是服务注册与发现相关的元数据，又回到了问题1，因为只有我自己在做 arpc 和 nbio，没有那么多精力去做微服务全套的东西，所以 arpc 的定位是基础设施，用户可以比较方便地自行定制即可。
而且，大而全的微服务框架又存在另一些悖论：
1. 大厂通常都是自家团队定制，不需要用开源的框架
2. 中小厂的业务量级，微服务乱拆分反而全链条成本增加、稳定性受损、问题排查难度增加
3. 对于很多中小项目，这些大而全的功能其实用不上，反倒增加了使用者的学习难度

**Comment by lesismal** [comment]
Sorry, forgot to ask, do you speak Chinese? If you don't, I will reply again in English.

**Comment by landbed** [comment]
Thanks man, I see what you mean, It is always best to keep it simple.
