### ISSUE TITLE
有没有tg 或者qq群组 , 拉一个呗

### ISSUE THREAD

**Issue by shoaly** [lesismal/arpc#14]
想要交流一下

**Comment by lesismal** [comment]
> 想要交流一下

多数情况 github 就可以了，拉群组可能会消耗比较多的时间在社交上，所以暂时不考虑。以后或许会考虑开个 slack 频道

**Comment by shoaly** [comment]
哈哈其实 大多数项目的群.... ownner都不怎么发言的, 组员多个交流的地方, 也能听到一些改进的建议.. 不过仁者见仁了.. 我先关掉了

**Comment by lesismal** [comment]
> 目的群.... ownner都不怎么发言的, 组员多个交流的地方, 也能听到一些改进的建议.. 不

好的，感谢老铁关注和建议！以后如果我有更多时间了再考虑开个群 :smile:

**Comment by lesismal** [comment]
开了 slack 频道，大家可以这里交流：
[arpc && nbio](https://join.slack.com/t/arpcnbio/shared_invite/zt-vh3g1z2v-qqoDp1hQ45fJZqwPrSz4~Q)
