### ISSUE TITLE
问一下 server 调用 client代码的样例 感觉我没用对, 又不知道哪里没对, 最终导致异常了

### ISSUE THREAD

**Issue by shoaly** [lesismal/arpc#18]
我的想问问 当 client 和 server已经连通之后,  在什么样的时机或者机制可以 通过ctx.Client.Call(....)
我的实际场景是, 当server拿到客户端传过来的数据之后,  需要经过耗时的运算, 然后将server的数据再通过同一个tcp连接 传回去, 但是不太方便直接在 在 server的handler中直接 ctx.Write().  所以才想到用server端去"call client"

## client端
```

client, err := arpc.NewClient(func() (net.Conn, error) {
    return net.DialTimeout("tcp", "localhost:10001", time.Second*3)
})
	

payload := Payload{}
client.Call("/send_payload", &payload, &rsp, time.Second*2)

client.Handler.Handle("/receive_payload", func(ctx *arpc.Context) {

    log.Print("server call received")
    var payload protocol.Payload
    
    if err := ctx.Bind(&payload); err == nil {
	    log.Print("req payload: ", payload.ToString())
	    ctx.Write([]byte("ok"))
    }
})
```

## server端 出错的的案例

```
server := arpc.NewServer()
    
    ready_chan := make(chan bool)
    server.Handler.Handle("/send_payload", func(ctx *arpc.Context) {
    var payload protocol.Payload
    
    if err := ctx.Bind(&payload); err == nil {
	    log.Print("req payload: ", payload.ToString())
	    client = ctx.Client
	    ctx.Write([]byte("ok"))
	    ready_chan <- true
    }
    })
    
    go func() {
    <-ready_chan
    log.Print("ctx.Client", client) // 这一行注释掉就崩了, 异常参见下一个段落
    res := ""
    
    payload := protocol.NewPayload(
	    1,
	    1,
	    1,
	    []byte("server call client"),
    )
    client.Call("/receive_payload", &payload, &res, time.Second*20)
    log.Print(fmt.Sprintf("server call client, req:%s, res:%s", payload.ToString(), res))
    
    }()
    
    server.Run("localhost:10001")


```

## 上面写法异常也看不到程序本身的行数, 应该是有地方没 recover到
```
2021/09/09 15:16:13.832 [ERR] runtime error: runtime error: invalid memory address or nil pointer dereference
traceback:
goroutine 25 [running]:
runtime/debug.Stack(0xc000107c20, 0x1b6980, 0x2bf960)
        c:/go/src/runtime/debug/stack.go:24 +0xa5
github.com/lesismal/arpc/util.Recover()
        C:/Users/go/pkg/mod/github.com/lesismal/arpc@v1.1.10/util/util.go:21 +0x5e
panic(0x1b6980, 0x2bf960)
        c:/go/src/runtime/panic.go:969 +0x1c7
github.com/lesismal/arpc.(*handler).OnMessage(0xc0000bc000, 0xc0000ba000, 0xc00001c200)
        C:/Users/go/pkg/mod/github.com/lesismal/arpc@v1.1.10/handler.go:596 +0x2f4
github.com/lesismal/arpc.(*Client).recvLoop(0xc0000ba000)
        C:/Users/go/pkg/mod/github.com/lesismal/arpc@v1.1.10/client.go:735 +0x2bf
github.com/lesismal/arpc/util.Safe(0xc00003e520)
        C:/Users/go/pkg/mod/github.com/lesismal/arpc@v1.1.10/util/util.go:28 +0x50
created by github.com/lesismal/arpc.(*Client).run
        C:/Users/go/pkg/mod/github.com/lesismal/arpc@v1.1.10/client.go:680 +0x108
```

**Comment by lesismal** [comment]
handler 函数的结束不代表 Context 的结束，是可以在 handler 之外异步执行后再调用 ctx.Write 的，比如

```golang
svr.Handler.Handle("Hello", func(ctx *arpc.Context) {
	go func() { // 或者使用您定制的协程池
		req := &HelloReq{}
		ctx.Bind(req)
		ctx.Write(&HelloRsp{Msg: req.Msg})
	}()
})
```

也正是因为觉得传统 RPC 的函数返回即调用结束的不友好、以及其他一些不便利，所以我才造了 ARPC :joy:

**Comment by lesismal** [comment]
关于异常看不到行数，我这里试了下：
```golang
package main

import (
	"fmt"

	"github.com/lesismal/arpc"
)

func main() {
	svr := arpc.NewServer()
	svr.Handler.Handle("/echo", func(ctx *arpc.Context) {
		var m []int
		fmt.Println(m[3])
	})
	svr.Run("localhost:8888")
}
```

Output:
```sh
PS D:\dev\gopath\src\github.com\lesismal\arpc\examples\rpc> go run .\server\
2021/09/09 16:27:59.593 [INF] [ARPC SVR] Running On: "127.0.0.1:8888"
2021/09/09 16:28:03.192 [INF] [ARPC SVR]        127.0.0.1:54149 Connected
2021/09/09 16:28:03.201 [ERR] runtime error: runtime error: index out of range [3] with length 0
traceback:
goroutine 12 [running]:
runtime/debug.Stack()
        D:/dev/go/src/runtime/debug/stack.go:24 +0x65
github.com/lesismal/arpc/util.Recover()
        D:/dev/gopath/src/github.com/lesismal/arpc/util/util.go:21 +0x3d
panic({0x837b80, 0xc000610000})
        D:/dev/go/src/runtime/panic.go:1038 +0x215
main.main.func1(0x813f0b)
        D:/dev/gopath/src/github.com/lesismal/arpc/examples/rpc/server/server.go:13 +0x1a
github.com/lesismal/arpc.(*handler).handle.func2(0xc0001126c0)
        D:/dev/gopath/src/github.com/lesismal/arpc/handler.go:515 +0x22
github.com/lesismal/arpc.(*Context).Next(...)
        D:/dev/gopath/src/github.com/lesismal/arpc/context.go:114
github.com/lesismal/arpc.(*handler).OnMessage(0xc0005a00f0, 0xc000140000, 0xc00008df50)
        D:/dev/gopath/src/github.com/lesismal/arpc/handler.go:592 +0x718
github.com/lesismal/arpc.(*Client).recvLoop(0xc000140000)
        D:/dev/gopath/src/github.com/lesismal/arpc/client.go:727 +0x264
github.com/lesismal/arpc/util.Safe(0x0)
        D:/dev/gopath/src/github.com/lesismal/arpc/util/util.go:28 +0x3e
created by github.com/lesismal/arpc.(*Client).run
        D:/dev/gopath/src/github.com/lesismal/arpc/client.go:684 +0x1b2
```

```sh
D:/dev/gopath/src/github.com/lesismal/arpc/examples/rpc/server/server.go:13 +0x1a
```

是可以看到的，您能提供一个完整的示例吗？

**Comment by shoaly** [comment]
client

```
package main

import (
	"log"
	"net"
	"tcpaio/protocol"
	"time"

	"github.com/lesismal/arpc"
)

type Sender struct {
}

func (sender Sender) Send() {
	client, err := arpc.NewClient(func() (net.Conn, error) {
		// return net.DialTimeout("tcp", "localhost:4001", time.Second*3)
		return net.DialTimeout("tcp", "localhost:10001", time.Second*3)
	})
	if err != nil {
		panic(err)
	}
	defer client.Stop()

	rsp := ""

	payload := protocol.NewPayload(
		1,
		1,
		1,
		[]byte("hello2"),
	)

	err = client.Call("/send_payload", &payload, &rsp, time.Second*2)
	if err != nil {
		log.Fatalf("Call failed: %v", err)
	} else {
		log.Printf("Call Response: \"%v\"", rsp)
	}

	client.Handler.Handle("/receive_payload", func(ctx *arpc.Context) {

		log.Print("server call received")
		var payload protocol.Payload

		if err := ctx.Bind(&payload); err == nil {
			log.Print("req payload: ", payload.ToString())
			ctx.Write([]byte("ok from client"))
		}
	})

	select {}
}


```


server.go

```

package main

import (
	"fmt"
	"log"
	"tcpaio/protocol"
	"time"

	"github.com/lesismal/arpc"
)

type Receiver struct {
}

var client *arpc.Client

func (receiver Receiver) Receive() {
	server := arpc.NewServer()

	server.Handler.Handle("/send_payload", func(ctx *arpc.Context) {
		var payload protocol.Payload

		if err := ctx.Bind(&payload); err == nil {
			log.Print("req payload: ", payload.ToString())
			client = ctx.Client
			ctx.Write([]byte("ok"))

			res := ""

			payload := protocol.NewPayload(
				1,
				1,
				1,
				[]byte("server call client"),
			)
			client.Call("/receive_payload", &payload, &res, time.Second*20)
			log.Print(fmt.Sprintf("server call client, req:%s, res:%s", payload.ToString(), res))

		}
	})

	server.Run("localhost:10001")

}


```

main.go

```
package main

import (
	"fmt"
	"log"
	"net"
)

func main() {


	sender := Sender{}
	go sender.Send()

	receiver := Receiver{}
	go receiver.Receive()

	select {}
}


```

**Comment by shoaly** [comment]
> handler 函数的结束不代表 Context 的结束，是可以在 handler 之外异步执行后再调用 ctx.Write 的，比如
> 
> ```go
> svr.Handler.Handle("Hello", func(ctx *arpc.Context) {
> 	go func() { // 或者使用您定制的协程池
> 		req := &HelloReq{}
> 		ctx.Bind(req)
> 		ctx.Write(&HelloRsp{Msg: req.Msg})
> 	}()
> })
> ```
> 
> 所以您不必像您提供的示例那样额外使用个chan来管理异步相关的流程。
> 
> 另外，arpc 虽然提供了 server Call client，但 Call 本身是阻塞的，如果需要使用 server Call client 的场景，您需要知道并 接受/正确处理 它的问题：比如不适合用于广播，免得线头阻塞（某个 client 阻塞导致其他连接等待）。但是可以使用 CallAsync，或者，如果您只是传递数据、不需要 client 回复，可以使用 Notify，相当于只推送消息给另一端不需要 response
> 
> 也正是因为觉得传统 RPC 的函数返回即调用结束的不友好、以及其他一些不便利，所以我才造了 arpc 😂

如果client.Call()  设置了 3秒超时,  server端等个5 6秒 才用 ctx.Write(...)  去写数据, 会崩么

**Comment by lesismal** [comment]
> 如果client.Call() 设置了 3秒超时, server端等个5 6秒 才用 ctx.Write(...) 去写数据, 会崩么

不会崩，但是client.Call 会返回err。如果你确定server端需要5、6秒，client.Call 超时时间可以设置久一点。

或者如果你不想阻塞，可以client.Call 时 server 像现在这样立即 ctx.Write("")，然后 server 处理完之后 client.Notify:

客户端注册接收数据的路由 `/your_method`：
```golang
client.Handler.Handle("/your_method", func(ctx *arpc.Context) {
	// receive data
})
```

服务端立即返回，处理完成后通过 `/your_method` 发送数据给客户端
```golang
svr.Handler.Handle("receive_payload", func(ctx *arpc.Context) {
	// do something
	ctx.Write("")

	go func() { //
		// do something
		ctx.Client.Notify("/your_method", yourData, time.Second)
	}()
})
```

**Comment by shoaly** [comment]
那意思是其实可以用:
[client] clinet.Notify -> server
[server] ctx.Client.Notify() -> client,    通过超时和或者err 去判断单次传输失败, 然后设法重传么?

**Comment by lesismal** [comment]
> client.Handler.Handle("/receive_payload", func(ctx *arpc.Context) {
> 
> 		log.Print("server call received")
> 		var payload protocol.Payload
> 
> 		if err := ctx.Bind(&payload); err == nil {
> 			log.Print("req payload: ", payload.ToString())
> 			ctx.Write([]byte("ok from client"))
> 		}
> 	})

路由注册应该放在通讯交互的前面，先 Handle("/xx", ...) 注册后，再调用 Call 之类的，就不会panic了。

**Comment by shoaly** [comment]
复现 这个 异常了么, 我这里改成notify 也会提示那个异常 ...

**Comment by lesismal** [comment]
您的例子中没有提供完整的包依赖 `"tcpaio/protocol"`，我改成普通的结构体，然后修改了您的例子，可以以这个作为参考：
```golang
package main

import (
	"log"
	"net"
	"time"

	"github.com/lesismal/arpc"
)

type Payload struct {
	A int
	B int
	C int
	D []byte
}

type Receiver struct {
}

func (receiver Receiver) Receive() {
	server := arpc.NewServer()

	server.Handler.Handle("/send_payload", func(ctx *arpc.Context) {
		reqPayload := Payload{}

		if err := ctx.Bind(&reqPayload); err == nil {
			log.Printf("server recv req payload: %v", reqPayload)
			resPayload := Payload{
				1,
				1,
				1,
				[]byte("server call client"),
			}
			err := ctx.Write(&resPayload)
			log.Printf("server send res payload: %v, error: %v", resPayload, err)
		}
	})

	server.Run("localhost:10001")
}

type Sender struct {
}

func (sender Sender) Send() {
	client, err := arpc.NewClient(func() (net.Conn, error) {
		// return net.DialTimeout("tcp", "localhost:4001", time.Second*3)
		return net.DialTimeout("tcp", "localhost:10001", time.Second*3)
	})
	if err != nil {
		panic(err)
	}
	defer client.Stop()

	reqPayload := Payload{
		A: 1,
		B: 1,
		C: 1,
		D: []byte("hello2"),
	}
	resPayload := Payload{}

	// 加大 timeout 时间，直接收取结果
	err = client.Call("/send_payload", &reqPayload, &resPayload, time.Second*10)
	if err != nil {
		log.Fatalf("Call failed: %v", err)
	} else {
		log.Printf("client recv res payload: %v", resPayload)
	}
	// 如果此处不想阻塞，可以用协程池或者直接go func()来执行
	// go func() {
	// 	err = client.Call("/send_payload", &reqPayload, &resPayload, time.Second*10)
	// 	if err != nil {
	// 		log.Fatalf("Call failed: %v", err)
	// 	} else {
	// 		log.Printf("client recv res payload: %v", resPayload)
	// 	}
	// }()

	select {}
}

func main() {
	receiver := Receiver{}
	go receiver.Receive()

	// 确保 server 已经监听端口、启动成功
	time.Sleep(time.Second)

	sender := Sender{}
	go sender.Send()

	select {}
}
```

**Comment by shoaly** [comment]
> > client.Handler.Handle("/receive_payload", func(ctx *arpc.Context) {
> > ```
> >   log.Print("server call received")
> >   var payload protocol.Payload
> > 
> >   if err := ctx.Bind(&payload); err == nil {
> >   	log.Print("req payload: ", payload.ToString())
> >   	ctx.Write([]byte("ok from client"))
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > })
> 
> 路由注册应该放在通讯交互的前面，先 Handle("/xx", ...) 注册后，再调用 Call 之类的，就不会panic了。

可以了, 确实是这样..... 麻烦在问一下这个问题的最佳实践:,  在数据单向传输的场景中是否都可以用notify 替换掉call 

[client] clinet.Notify -> server
[server] ctx.Client.Notify() -> client, 通过超时和或者err 去判断单次传输失败, 然后设法重传么?
因为在我的场景中, 主要是数据的从server->client 和 client->server的 单向传递, 所以之前直接就返回了一个"ok", 看来用notify 替代call 更合适

**Comment by lesismal** [comment]
协议层的几种交互模式：

| Pattern | Interactive Directions       | Description              |
| ------- | ---------------------------- | ------------------------ |
| call    | two-way:<br>c -> s<br>s -> c | request and response     |
| notify  | two-way:<br>c -> s<br>s -> c | request without response |


最佳实践根据实际项目来就行，比如只需要发送数据给对方，就对方注册个路由，发送方用 Notify 就行。如果连接状态不佳发送时间长、连接断开发送失败等情况，应该由业务层的断线重连后初始化、更新数据相关的逻辑保障。

**Comment by lesismal** [comment]
> [client] clinet.Notify -> server
> [server] ctx.Client.Notify() -> client, 通过超时和或者err 去判断单次传输失败, 然后设法重传么?
> 因为在我的场景中, 主要是数据的从server->client 和 client->server的 单向传递, 所以之前直接就返回了一个"ok", 看来用notify 替代call 更合适

对，可以这样。相比于传统的 RPC 框架，arpc支持的姿势比较多，基本能满足各类需要，具体的用法是要看你们实际业务的需要来实施。

**Comment by shoaly** [comment]
谢谢, 回复的很详细了

**Comment by lesismal** [comment]
> 谢谢, 回复的很详细了

不客气，good luck!

**Comment by shoaly** [comment]
对了在问一下....

**Comment by lesismal** [comment]
> 对了在问一下.... client 和server链接建立之后, 需要自己定时send小包 来保持链接不断开么... 有时候tcp链接会被强行关闭

我默认没有提供 heartbeat，因为应用层自己实现一个 heartbeat 太简单了，只要加一个路由或者 Call(“”, ...)，client 端 for ticker Call 就行了。
```golang
go func() {
	ticker := time.NewTicker(your_keepalive_time)
	for someRunningFlag {
		<-ticker.C
		client.Call("/your_heartbeat_method")
		//或者（arpc会默认注册个 "" 的handler）
		// client.Call("")
	}
}()
```

需要进行超时断开的一端，可以通过 Handler.BeforeRecv 来设置：
```golang
arpc.DefaultHandler.BeforeRecv(func(conn net.Conn) error {
	return conn.SetReadDeadline(time.Now().Add(your_timeout))
})
```

**Comment by lesismal** [comment]
HandleConnected 中可以设置conn的属性，比如

```golang
server.Handler.HandleConnected(func(client *arpc.Client) {
	tcpConn, _ := client.Conn.(*net.TCPConn)
	tcpConn.SetKeepAlive(true)
	tcpConn.SetKeepAlivePeriod(your_keepalive_period)
})
```

可以根据你们的实际需要进行定制

**Comment by shoaly** [comment]
> HandleConnected 中可以设置conn的属性，比如
> 
> ```go
> server.Handler.HandleConnected(func(client *arpc.Client) {
> 	tcpConn, _ := client.Conn.(*net.TCPConn)
> 	tcpConn.SetKeepAlive(true)
> 	tcpConn.SetKeepAlivePeriod(your_keepalive_period)
> })
> ```
> 
> 可以根据你们的实际需要进行定制

所以这是两个方案么, 一个是 定时器调用 .Call ,  另外一种是 server端的 HandleConnected 里面将 conn.SetKeepAlive(true)

**Comment by lesismal** [comment]
> > HandleConnected 中可以设置conn的属性，比如
> > ```go
> > server.Handler.HandleConnected(func(client *arpc.Client) {
> > 	tcpConn, _ := client.Conn.(*net.TCPConn)
> > 	tcpConn.SetKeepAlive(true)
> > 	tcpConn.SetKeepAlivePeriod(your_keepalive_period)
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以根据你们的实际需要进行定制
> 
> 所以这是两个方案么, 一个是 定时器调用 .Call , 另外一种是 server端的 HandleConnected 里面将 conn.SetKeepAlive(true)

这是两个不同层次的设置，tcp的keepalive是4层，未必能满足7层的需要。比如4层保活未断开，但是7层没有数据交互已经算是僵尸连接。
你们可以根据自己的需要进行处理，通常是定时Call来保证7层的活跃性。

**Comment by lesismal** [comment]
这个 issue 如果没有更多问题了就准备关闭了

开了 slack 频道，大家可以这里交流：
[arpc && nbio](https://join.slack.com/t/arpcnbio/shared_invite/zt-vh3g1z2v-qqoDp1hQ45fJZqwPrSz4~Q)

**Comment by shoaly** [comment]
有一个小问题,   也是从这个地方延伸的,  不晓得有没有可能 在 server.Client.Call的时候 检查一下 Client是否已经注册过路由, 没有的话提示一个handler not existed的异常.... 开发过程中 还是容易写错路由....~~~

**Comment by lesismal** [comment]
我上面有讲过，虽然提供了server call client 的方法，但通常不应该这样做、尤其如果涉及广播业务（因为Call可能阻塞一段时间），需要client响应可以使用 CallAsync，否则可以Notify。 

一方没有注册路由并收到该路由请求时会响应error：https://github.com/lesismal/arpc/blob/master/handler.go#L611 ，这可以用于判断，但几乎没有人会用这种 “先判断对方是否注册了该路由” 的方式，这种需求属于 “不好的甚至错误的设计”。

另外，client 连接成功后可以先 call 一下 server 来声明自己监听了哪些路由并且 server 端 client.Set，后续 server 可以进行你上面提到的判断。单考虑匹配事件分发的情况，pub/sub的与这种比较类似，比如 pub/sub 的client，订阅过消息的 client 断开连接、重连成功后也会 call 一次初始化自己新connection在 server 段的订阅: 
https://github.com/lesismal/arpc/blob/master/extension/pubsub/client.go#L208

**Comment by shoaly** [comment]
> 我上面有讲过，虽然提供了server call client 的方法，但通常不应该这样做、尤其如果涉及广播业务（因为Call可能阻塞一段时间），需要client响应可以使用 CallAsync，否则可以Notify。
> 
> 一方没有注册路由并收到该路由请求时会响应error：https://github.com/lesismal/arpc/blob/master/handler.go#L611 ，这可以用于判断，但几乎没有人会用这种 “先判断对方是否注册了该路由” 的方式，这属于 “不好的甚至错误的设计”。
> 
> 另外，client 连接成功后可以先 call 一下 server 来声明自己监听了哪些路由并且 server 端 client.Set，后续 server 可以进行你上面提到的判断。单考虑匹配事件分发的情况，pub/sub的与这种比较类似，比如 pub/sub 的client，订阅过消息的 client 断开连接、重连成功后也会先 call 来初始化自己新的 connection 在 server 端的订阅:
> https://github.com/lesismal/arpc/blob/master/extension/pubsub/client.go#L208

恩 是用的notify,  可以关掉这个 issue了, 谢谢热心解答
