### ISSUE TITLE
Server 内部 clients是否可以对外公开?

### ISSUE THREAD

**Issue by fyyang** [lesismal/arpc#19]
因为我看内部已经实现了 客户端的记录, 这样这样也不用我们重新实现. 例如 Broadcast  还要自己存储 `var clientMap = make(map[*arpc.Client]struct{})`

可能要换成读写锁了

**Comment by lesismal** [comment]
```golang
var clientMap = make(map[*arpc.Client]struct{})` 
```

这种不方便按条件查找

业务层通常有自家对应的数据结构，比如按id存储client：
```golang
var users = map[int64]*aprc.Client{}

client, ok := users[id]
// ...

// or

type User struct{
    Client *arpc.Client

    // some other fields
}
var users = map[int64]*User {}

user, ok := users[id]
// ...
```

server 里的 clients 目前主要用于最大在线数控制和退出清理，只在客户端连接、断开、server退出时才会add/delete、属于少量操作，client连接成功后、退出前的多次交互中不会有add/delte/foreach等操作，性能影响可以忽略，业务层自己额外加个管理更能贴近业务需要。
Broadcast针对不同的业务场景，可能需要client认证，认证成功后才会加入到管理中、需要认证的业务场景，广播时不应该把消息发送给未经过认证的client，如果使用这种统一的需要额外增加广播的filter函数参数进行过滤、每次广播要对每个连接进行一次filter条件判断的计算、性能不如认证后再加入管理，melody的websocket封装是这种封装、虽然性能影响不大但不是最佳方案。

> 可能要换成读写锁了

RWMutex 比 Mutex 消耗更多，在一些竞争很少的场景，RWMutex 不如 Mutex 划算。如果明确业务层面存在多并发流的读需求并且频率很高容易触发锁竞争，则可以考虑使用 RWMutex。但是在go领域，通常为了业务逻辑简单会使用 goroutien+chan 把逻辑串行化，所以业务层可能连锁都不需要加。

**Comment by lesismal** [comment]
业务层自己封装一个管理器很容易。

倒是也可以考虑提供 Broadcast、ForEach 之类的方法，但是不能提供 server.Clients 返回client集合，因为 clients 需要锁保护，并不是返回给业务层了业务层就可以直接操作的，如果返回一份拷贝那性能就很不划算了

**Comment by lesismal** [comment]
发布了 v1.2.2 新增接口: server.Broadcast/BroadcastWithFilter/ForEach/ForEachWithFilter

example:
https://github.com/lesismal/arpc/blob/master/examples/broadcast/server/server.go#L46

看下这样好用不

**Comment by fyyang** [comment]
`func (s *Server) BroadcastWithFilter(method string, v interface{}, filter func(*Client) bool, args ...interface{}) {
	msg := s.NewMessage(CmdNotify, method, v, args...)
	s.mux.Lock()
	defer func() {
		msg.Release()
		s.mux.Unlock()
	}()

	for c := range s.clients {
		if filter == nil || filter(c) {
			msg.Retain()
			c.PushMsg(msg, TimeZero)
		}
	}
}

func (s *Server) ForEach(h func(*Client)) {
	s.mux.Lock()
	defer s.mux.Unlock()
	for c := range s.clients {
		h(c)
	}
}

func (s *Server) ForEachWithFilter(h func(*Client), filter func(*Client) bool) {
	s.mux.Lock()
	defer s.mux.Unlock()
	for c := range s.clients {
		if filter == nil || filter(c) {
			h(c)
		}
	}
}`
能满足是能满足, 但是这种情况确实是读场景比较多(当然两种都可以). 确实有时候需要根据自己业务需求进行client分组. 
之后如果我有新的想法和需求, 我再进行PR吧

**Comment by lesismal** [comment]
> 能满足是能满足, 但是这种情况确实是读场景比较多(当然两种都可以). 确实有时候需要根据自己业务需求进行client分组.
> 之后如果我有新的想法和需求, 我再进行PR吧

你的意思是想换 RWMutex 吧？绝大多数业务没这个必要：
1. 非阻塞的 PushMsg，连接数不是特别巨大的情况下，通常很快、并发触发竞争的概率也很小
2. 业务层最好是按模块 goroutine+chan 串行化操作，所以多数可以规避掉并发竞争
3. Mutex 可以保证多并发流 Broadcast 时候每个 client 的消息顺序，如果是 RWMutex，可能两个 goroutine A/B ，A 先广播、广播了一半 client 时被调度了，然后 B 广播了全部 client，这些 client 收到的两条消息顺序可能不一致，框架层针对通用业务，还是确保这个顺序要好些

所以，有特殊需要的话还是业务层自己定制更好些

**Comment by fyyang** [comment]
emmm, 读写锁, 读的时候不能写

> 3\. Mutex 可以保证多并发流 Broadcast 时候每个 client 的消息顺序，如果是 RWMutex，可能两个 goroutine A/B ，A 先广播、广播了一半 client 时被调度了，然后 B 广播了全部 client，这些 client 收到的两条消息顺序可能不一致，框架层针对通用业务，还是确保这个顺序要好些

**Comment by lesismal** [comment]
> , 读写锁, 读的时候

emmm，如果用读写锁，A/B两个广播都是RLock/RUnlock。

**Comment by lesismal** [comment]
其他一些高性能的场景，通常也会使用 Mutex 而不是 RWMutex，比如一些缓存项目的实现，因为真正触发锁竞争的场景非常少，用 RWMutex 收益小于损失。
所以不必盲目按照 RWMutex 能够实现的效果来使用它。

**Comment by fyyang** [comment]
emmm, 发了你封google 邮件
