### ISSUE TITLE
可以增加一个最大重试次数限制或者回调么？

### ISSUE THREAD

**Issue by spxvszero** [lesismal/arpc#21]
我在使用的过程中，发现通过 Client 建立的请求，当 Server 端意外失联之后，Client 端会不断的尝试重连，重试间隔 1s，无法中断，查看 client.go 的代码后发现有如下逻辑：

https://github.com/lesismal/arpc/blob/b7b66250afb12b445295063631cb8072a35f0788/client.go#L752-L771

期望：
是否可以在此处增加重连次数的回调？可以让调用者决定多少次之后放弃重新建立连接，转而处理其他业务？
如果考虑到 Handler 的调用次数可能过于频繁的话，那是否可以在 Client 的配置中增加个限制最大重试次数，超过之后直接走 Disconnected 的 Handler，这个 Disconnected 的 Handler 目前似乎只有在 Client 端主动 Stop 的时候才会执行。

我尝试 fork 增加了部分相关代码，目前使用上是满足我的业务了，不过没有经过测试，也不敢提 pull request，所以在这里提出这个改进建议，谢谢阅读。

**Comment by lesismal** [comment]
1. 断线重连期间客户端 Call 会返回 ErrClientReconnecting，不会阻塞。应用层也可以自己判断下 err 做相关的定时退出处理。
2. 实际场景中这个次数未必有用，比如网络故障导致断开，重试次数配置了30次耗时30-60s然后 client 退出了，但2分钟后网络恢复了。如果不配置重试次数，2分钟后仍可恢复。最早考虑过重试次数限制，但出于实际场景的考虑，没有加这个。

可以描述下你的使用场景，比如加上重试次数限制后为什么能够满足需要，如果确实合理，可以考虑增加重试次数的限制。

**Comment by spxvszero** [comment]
我这边的场景是广播模式下的，Client 端通过 Call 一次 Server 端的鉴权之后，后续就一直监听 Server 端的 Boardcast 了，沿用这段示例代码
https://github.com/lesismal/arpc#broadcast---notify

由于后续 Client 端几乎不会执行 Call 方法，所以也无法获取到 Server 的  ErrClientReconnecting 状态，对于此时的 Client 端，只能一直保持着这种无限等待重连的状态，如果不加重试次数或者回调的话，Client 端的数据将长时间没法更新，应用终端可能在无法得知的情况下获取到旧数据。（当然也可以设置 Client 端一个定时的心跳机制去执行 Call 方法，不过这种情况下，我觉得有点多余也不好看了，假设有多个 Client 端，那就得维护多个心跳定时器了）

**Comment by lesismal** [comment]
> 我这边的场景是广播模式下的，Client 端通过 Call 一次 Server 端的鉴权之后，后续就一直监听 Server 端的 Boardcast 了，沿用这段示例代码 https://github.com/lesismal/arpc#broadcast---notify
> 
> 由于后续 Client 端几乎不会执行 Call 方法，所以也无法获取到 Server 的 ErrClientReconnecting 状态，对于此时的 Client 端，只能一直保持着这种无限等待重连的状态，如果不加重试次数或者回调的话，Client 端的数据将长时间没法更新，应用终端可能在无法得知的情况下获取到旧数据。（当然也可以设置 Client 端一个定时的心跳机制去执行 Call 方法，不过这种情况下，我觉得有点多余也不好看了，假设有多个 Client 端，那就得维护多个心跳定时器了）

但是如果client退出了，也不能继续获取新数据了，如果退出了那么后续你会怎么处理？如果是创建新的client，其实还不如就让它自己重连。如果是直接退出程序，那感觉可能会更糟

**Comment by spxvszero** [comment]
我这边会修改断掉这个 Client 获得的数据为离线，我的 Client 作用是一边监听多个不同端的 Server ，然后展示数据给应用的终端，也可以说是操作端，那么作为操作端这边，看到其中一个 Client 连接的数据状态改变了，那么检查完远端 Server 的状态之后，可以手动重启单独这个 Client。

现在主要问题就是，一个广播的 Server 端如果失联，Client 端的重连状态没法告诉应用端。无论应用端忽略也好，强制挂起也好，至少给应用端一个可以决定处理的方案，目前除了 Client 端主动去 Call 以外，无法知道当前 Client 是已经断开而且正在重连中的。

而且目前这种固定 1s 重连的机制我认为也是不太好的，如果 Server 端确认是出问题了，那么这个重连请求频率是不是太高了，我记得好像程序使用的重连策略，是会根据斐波那契数列递增的，最后会固定在一个相对合理的间隔上的，这样或许更合理一些。

**Comment by lesismal** [comment]
> 我这边会修改断掉这个 Client 获得的数据为离线，我的 Client 作用是一边监听多个不同端的 Server ，然后展示数据给应用的终端，也可以说是操作端，那么作为操作端这边，看到其中一个 Client 连接的数据状态改变了，那么检查完远端 Server 的状态之后，可以手动重启单独这个 Client。
> 
> 现在主要问题就是，一个广播的 Server 端如果失联，Client 端的重连状态没法告诉应用端。无论应用端忽略也好，强制挂起也好，至少给应用端一个可以决定处理的方案，目前除了 Client 端主动去 Call 以外，无法知道当前 Client 是已经断开而且正在重连中的。
> 
> 而且目前这种固定 1s 重连的机制我认为也是不太好的，如果 Server 端确认是出问题了，那么这个重连请求频率是不是太高了，我记得好像程序使用的重连策略，是会根据斐波那契数列递增的，最后会固定在一个相对合理的间隔上的，这样或许更合理一些。

其实 1s 是个比较折中的时长。递增的时长适合一些场景，比如 server 端 accept 的快速恢复:
https://github.com/golang/go/blob/master/src/net/http/server.go#L3019

client 数量不多的话，从较小的间隔起步、递增到一个最大值，这样来进行尽量快速的连接恢复。
但对于 rpc 连接断开，网络故障的概率大一些，如果起步间隔很小，较多 client 的场景下，如果网络迅速恢复了，反倒会短时间对 server 造成一点高频的冲击；
如果间隔很大，那么网络或者 server 恢复后，client 需要等待更久一点时间才能恢复。综合来看，1s 应该是绝大多数场景能够接受的方案。

对于修改 client 状态、后续检测 server 状态正常了再重启 client 的方案，也就是说即使你没有用固定的 Call 之类的方案来做状态保活，也仍然需要在得知断开后去做类似的操作，那可能还不如直接就带上默认的保活，代码反倒更简单些。
另外，如果 server 广播的频率存在最小间隔，也可以把存的数据加个 lastUpdateTime 字段，根据这个字段来判断数据是否为新（而且，不管 client 当前的数据是否为 server 端的最新，对于 client 自己而言，本地数据都是最后一次收到的数据、都是本地最新）

**Comment by spxvszero** [comment]
我对 Dial 的开销没有太多了解，只是觉得如果可能的话，尽量减少一些开销会好一些。假设我的 Client 端是为了监控 Server 端的服务状态，而 Server 端是主要业务的提供者，那么当 Server 端意外停机了，Client 端只能等到下一个 Call 的时刻才能知道 Server 端已经停止服务了。那么如果在 Client 中加了保活，那保活的间隔多久合适呢？也是 1s 么？但是本身 arpc 就是维护这个 tcp 通道的正常是否的，那么还有必要再用保活多做一层同样的工作呢？

话说如果我要计算 Client 端和 Server 端的延时，那么似乎需要自己去通过设置 Call 里面请求的序号，然后得到返回的相同的序号，才能计算出来吧。

**Comment by lesismal** [comment]
Handler 新增了 MaxReconnectTimes/SetMaxReconnectTimes ，小于等于0还是无限次数重连（默认0，与老版本兼容），我简单测了下应该可以了，暂时没发布新版本，你试下 master 最新的看看这样 ok 不：
go get -u github.com/lesismal/arpc@e8e64ed

如果确认 ok，我发个新版本

**Comment by spxvszero** [comment]
我测试了下，可以满足我目前的需要，如果可以返回是因为什么原因导致的 Disconencted 那就太好了。

在测试过程中出现了一些问题，导致我有点怀疑手动保活是否比 arpc 的自动重连更可靠了。

1、在测试中，如果 Server 端主动中断，那么 Client 端会收到一个 EOF 消息断开连接，然后进入重连流程。但是如果 Server 端服务良好，只是网络中断的情况下，Client 端需要花费两三分钟之后才能确定和 Server 端断开连接，此时才进入重连流程。

2、还有一次是重连的间隔超过了 1s ，日志中显示是 5s 左右，这个间隔时间持续了整个重连流程，不知道是不是 goroutine 的优先级分配问题导致的，由于只出现过一次，后面再次进入重连流程的时候就正常了，我就没有深究了。

尽管如此，我还是认为提供更多的可选状态，给使用者更多的可操作空间并没有什么问题。感谢你的回复。

**Comment by lesismal** [comment]
> 我测试了下，可以满足我目前的需要，如果可以返回是因为什么原因导致的 Disconencted 那就太好了。

这个没太大必要，否则你需要去判断很多种错误类型，包括net包的错误，要确保覆盖所有断开错误本身也是个考验。

> 只是网络中断的情况下

不同情况下的中断，对方未必能立刻感知。比如设备掉电、路由丢包，EOF你都可能收不到，所以应用层合理的心跳是比较好的，你可以在 Handler.BeforRecv 中加入这种超时设定来支持心跳相关的功能：

```golang
svr.Handler.BeforeRecv(func(c net.Conn) error {
	c.SetReadDeadline(yourKeepaliveTime)
})
```

通常客户端、服务端都可以设置这个超时，客户端小于这个间隔Call，确保在间隔时间内双方都能收到对方的包，调用失败则可以判断故障了。

> 还有一次是重连的间隔超过了 1s ，日志中显示是 5s 左右
重连代码中的 1s 只是 sleep 的时间，这个间隔是为了避免对另一端不必要的高频 Dial，不代表这一轮 Dial 整个时长是 1s，Dial 要三次握手，不通系统内核协议实现、tcp 老端口关闭后回收之类的，都可能影响 Dial 阻塞的时长。估计你测试的代码没什么瓶颈，所以这跟 goroutine 优先级没什么关系

**Comment by spxvszero** [comment]
感谢解惑～

**Comment by lesismal** [comment]
> 感谢解惑～

也感谢你的反馈 :smile:

增加重连次数配置对原来的逻辑没有侵入式影响，所以也发布到新版本了：
https://github.com/lesismal/arpc/releases/tag/v1.2.3
