### ISSUE TITLE
可否实现一下关于 coder 的解耦？

### ISSUE THREAD

**Issue by Invincibl-e** [lesismal/arpc#24]
由 coder 实现人提供 bodyLength，目前看代码唯一的方法就是在 buff 最前加上指定的大小，或者可以由 coder 实现人提供一个函数，来判断 request 是否已 read 完成？

**Comment by lesismal** [comment]
> 目前看代码唯一的方法就是在 buff 最前加上指定的大小

这样说不太准确。默认的coder是这样子，因为二进制的方式，相比结构化的方案更省字节数，性能也好，还想更省点的话就是连bodyLength都换成类似pb、ws协议头动态长度的（暴扣arpc header的bodyLength）

因为为了性能，高性能的rpc框架通常都不会不像http那样一行一个可见文本格式的header，http那样倒是方便了，但是太浪费字节数量和性能了

如果不在乎这点性能，用户coder可以用一个灵活的可序列化格式包裹原来的body，比如arpc body用一个大json，其中一个字段是Call/Notify本身的body，这样coder就可以自由添加字段了、像http那样方便，但是当然会牺牲性能和流量

**Comment by lesismal** [comment]
提交了个 msgpack 的扩展，扩展也主要是用于示例，用户根据需要定制就好：
https://github.com/lesismal/arpc/commit/168b8d754cd27d3c8d1bb8bb8bdfef190acb243b

**Comment by Invincibl-e** [comment]
> 提交了个 msgpack 的扩展，扩展也主要是用于示例，用户根据需要定制就好： [168b8d7](https://github.com/lesismal/arpc/commit/168b8d754cd27d3c8d1bb8bb8bdfef190acb243b)

我一开始使用 protobuf 做实现之后，发现 invalid length， 然后没办法只能把第一个 bodyLen 字节填充了。。。诚然使用默认的 coder 确实省流量，提高性能，但是对跨语言不够友好。

**Comment by Invincibl-e** [comment]
> > > 提交了个 msgpack 的扩展，扩展也主要是用于示例，用户根据需要定制就好： [168b8d7](https://github.com/lesismal/arpc/commit/168b8d754cd27d3c8d1bb8bb8bdfef190acb243b)
> > 
> > 
> > 我一开始使用 protobuf 做实现之后，发现 invalid length， 然后没办法只能把第一个 bodyLen 字节填充了。。。诚然使用默认的 coder 确实省流量，提高性能，但是对跨语言不够友好。
> 
> 可以参考下我新提交的msgpack的，`invalid length`估计是你没有设置正确的BodyLen吧。如果性能不敏感、这样做还算凑合吧 😂

现在没有问题了啊，我看您好像还是保留了整个 header，我这边只保留了 bodyLen 一个字段了，( headLen - 12  ) 之后的位置我都覆盖了，对比了下 protobuf 可变长编码和原生比较，差距并不不是很大，如果后续能增加一个接口给 Coder 来判断 packet 是否接收完成，也是极好的，当然现在也可以凑合😂。

**Comment by lesismal** [comment]
> 对比了下 protobuf 可变长编码和原生比较

pb本身也是不需要json那种key字段以及一堆引号冒号的，而且标示长度的字段是根据长度动态用的最小整形、如果结构简单可能比固定用16/32bit还省点

> 如果后续能增加一个接口给 Coder 来判断 packet 是否接收完成，也是极好的

你的 coder 里收到的 msg 已经是完整的了，不需要再判断是否已经接收完，接收的代码在这里，详细的可以自己看下：
https://github.com/lesismal/arpc/blob/master/handler.go#L558

**Comment by Invincibl-e** [comment]
> > 对比了下 protobuf 可变长编码和原生比较
> 
> pb本身也是不需要json那种key字段以及一堆引号冒号的，而且标示长度的字段是根据长度动态用的最小整形、如果结构简单可能比固定用16/32bit还省点
> 
> > 如果后续能增加一个接口给 Coder 来判断 packet 是否接收完成，也是极好的
> 
> 你的 coder 里收到的 msg 已经是完整的了，不需要再判断是否已经接收完，接收的代码在这里，详细的可以自己看下： https://github.com/lesismal/arpc/blob/master/handler.go#L558
> 
> 😄

这里我看到了，怎么处理，实际上都可以的。
