### ISSUE TITLE
PR REQ 关于端对端增强功能

### ISSUE THREAD

**Issue by Invincibl-e** [lesismal/arpc#25]
可否增加，当 client 连接到 server 之后，通过 client.handle  设置 method，当下次客户端推送消息时，直接将消息推送到对应的 client handle，不走 server handle 进行中转？

**Comment by lesismal** [comment]
没太懂，是指server自己accpt后创建的client，还是指创建client后dial到server上的client？

**Comment by Invincibl-e** [comment]
> 没太懂，是指server自己accpt后创建的client，还是指创建client后dial到server上的client？

server 自己 accpt 后创建的 client

**Comment by lesismal** [comment]
> > 没太懂，是指server自己accpt后创建的client，还是指创建client后dial到server上的client？
> 
> server 自己 accept 后创建的 client

带不来什么好处呀，为什么要这样做呢？

**Comment by Invincibl-e** [comment]
> > > 没太懂，是指server自己accpt后创建的client，还是指创建client后dial到server上的client？
> > 
> > 
> > server 自己 accept 后创建的 client
> 
> 带不来什么好处呀，为什么要这样做呢？

啊，我突然想到回调有传递 client 对象，是我封装的时候愚昧了。。。。关了，不丢人了

**Comment by lesismal** [comment]
> 啊，我突然想到回调有传递 client 对象，是我封装的时候愚昧了。。。。关了，不丢人了

没关系的，感谢关注和反馈！:smile:
