### ISSUE TITLE
panic: unaligned 64-bit atomic operation on 32 bit

### ISSUE THREAD

**Issue by Invincibl-e** [lesismal/arpc#26]
```
goroutine 38 [running]:
runtime/internal/atomic.panicUnaligned()
	C:/Program Files/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0x1212a09c, 0x1)
	C:/Program Files/Go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/lesismal/arpc.(*Client).newRequestMessage(0x1212a060, 0x1, {0x7946f350, 0x10}, {0x79457880, 0x11c68000}, 0x0, 0x1, {0x0, 0x0, ...})
	F:/Go/pkg/mod/github.com/lesismal/arpc@v1.2.3/client.go:564 +0x10d
github.com/lesismal/arpc.(*Client).CallAsync(0x1212a060, {0x7946f350, 0x10}, {0x79457880, 0x11c68000}, 0x7947da14, 0x12a05f200, {0x0, 0x0, 0x0})
```

貌似原子操作 32 位要对齐？

**Comment by lesismal** [comment]
看样子算是go的一个bug，proposal 似乎有计划：https://github.com/golang/go/issues/36606

我先更新了两个提交：
https://github.com/lesismal/arpc/commit/1af7123b86de30cdcb2a143633934d470c87acbe
https://github.com/lesismal/arpc/commit/5e01e30a99aaa70bdb7de747285739691e811a17

试下可以不：
```sh
go get github.com/lesismal/arpc@5e01e30
```

**Comment by lesismal** [comment]
btw，您是什么硬件、系统？嵌入式设备arm？

**Comment by Invincibl-e** [comment]
> 看样子算是go的一个bug，proposal 似乎有计划：[golang/go#36606](https://github.com/golang/go/issues/36606)
> 
> 我先更新了两个提交： [1af7123](https://github.com/lesismal/arpc/commit/1af7123b86de30cdcb2a143633934d470c87acbe) [5e01e30](https://github.com/lesismal/arpc/commit/5e01e30a99aaa70bdb7de747285739691e811a17)
> 
> 试下可以不：
> 
> ```shell
> go get github.com/lesismal/arpc@5e01e30
> ```

现在 OK 了。

**Comment by Invincibl-e** [comment]
> btw，您是什么硬件、系统？嵌入式设备arm？

打包成库，目标进程是 32 位的，不得已委屈求全。

**Comment by lesismal** [comment]
> 进程是 32 位的，不得已委

好的，发布了 [v1.2.4](https://github.com/lesismal/arpc/releases/tag/v1.2.4)
