### ISSUE TITLE
可以同时监听 WebSocket 协议和 raw socket 吗？

### ISSUE THREAD

**Issue by Invincibl-e** [lesismal/arpc#27]

**Comment by lesismal** [comment]
这具体是什么需求？
raw socket 是 ip 层，需要自己另外在其上封装可靠协议层作为 rpc 的基础。
如果是同一个端口，3层和7层混用这肯定是不合适的。

**Comment by Invincibl-e** [comment]
> 这具体是什么需求？ raw socket 是 ip 层，需要自己另外在其上封装可靠协议层作为 rpc 的基础。 如果是同一个端口，3层和7层混用这肯定是不合适的。

不同端口肯定的。。。。主要是 Web 层要访问 RPC，本来想着是做转发，但是看 ARPC 好像有个 websocket 扩展。

**Comment by lesismal** [comment]
所以只是为了复用 handler 吧？那就是跟 raw socket 无关。
复用 handler 可以这样：

server:
```golang
package main

import (
	"fmt"
	"log"

	"github.com/lesismal/arpc"
)

func main() {
	h := arpc.NewHandler()
	h.Handle("/echo", func(ctx *arpc.Context) {
		var str string
		ctx.Bind(&str)
		ctx.Write(str)
		log.Printf("echo from server[%v] to client[%v]", ctx.Client.Conn.LocalAddr(), ctx.Client.Conn.RemoteAddr())
	})

	svrs := make([]*arpc.Server, 3)[0:0]
	for port := 9000; port < 9003; port++ {
		svr := arpc.NewServer()
		svr.Handler = h
		go svr.Run(fmt.Sprintf("localhost:%d", port))
		svrs = append(svrs, svr)
	}

	<-make(chan int)
}
```

client:
```golang
package main

import (
	"fmt"
	"log"
	"net"
	"time"

	"github.com/lesismal/arpc"
)

func main() {
	echo := func(port int) {
		client, err := arpc.NewClient(func() (net.Conn, error) {
			return net.DialTimeout("tcp", fmt.Sprintf("localhost:%v", port), time.Second*3)
		})
		if err != nil {
			panic(err)
		}
		defer client.Stop()

		req := "hello"
		rsp := ""
		err = client.Call("/echo", &req, &rsp, time.Second*5)
		if err != nil {
			panic(err)
		}
		log.Printf("echo to server[%v] from client[%v]", client.Conn.RemoteAddr(), client.Conn.LocalAddr())
	}

	for port := 9000; port < 9003; port++ {
		echo(port)
	}
}
```

**Comment by Invincibl-e** [comment]
> 所以只是为了复用 handler 吧？那就是跟 raw socket 无关。 复用 handler 可以这样：
> 
> server:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 
> 	"github.com/lesismal/arpc"
> )
> 
> func main() {
> 	h := arpc.NewHandler()
> 	h.Handle("/echo", func(ctx *arpc.Context) {
> 		var str string
> 		ctx.Bind(&str)
> 		ctx.Write(str)
> 		log.Printf("echo from server[%v] to client[%v]", ctx.Client.Conn.LocalAddr(), ctx.Client.Conn.RemoteAddr())
> 	})
> 
> 	svrs := make([]*arpc.Server, 3)[0:0]
> 	for port := 9000; port < 9003; port++ {
> 		svr := arpc.NewServer()
> 		svr.Handler = h
> 		go svr.Run(fmt.Sprintf("localhost:%d", port))
> 		svrs = append(svrs, svr)
> 	}
> 
> 	<-make(chan int)
> }
> ```
> 
> client:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 	"net"
> 	"time"
> 
> 	"github.com/lesismal/arpc"
> )
> 
> func main() {
> 	echo := func(port int) {
> 		client, err := arpc.NewClient(func() (net.Conn, error) {
> 			return net.DialTimeout("tcp", fmt.Sprintf("localhost:%v", port), time.Second*3)
> 		})
> 		if err != nil {
> 			panic(err)
> 		}
> 		defer client.Stop()
> 
> 		req := "hello"
> 		rsp := ""
> 		err = client.Call("/echo", &req, &rsp, time.Second*5)
> 		if err != nil {
> 			panic(err)
> 		}
> 		log.Printf("echo to server[%v] from client[%v]", client.Conn.RemoteAddr(), client.Conn.LocalAddr())
> 	}
> 
> 	for port := 9000; port < 9003; port++ {
> 		echo(port)
> 	}
> }
> ```

测试没有问题，照着样例建立了 websocket 同时共用一个 handler。Q-Q
