### ISSUE TITLE
Server restart does not trigger HandleConnected

### ISSUE THREAD

**Issue by fyyang** [lesismal/arpc#3]
Server restart, client reconnection does not trigger HandleConnected AND HandleDisconnected

**Comment by fyyang** [comment]
sorry, 大意了, 没有闪

**Comment by landbed** [comment]
@lesismal 

It seems only ```OnDisconnected``` called, but ```OnConnected``` not on client side, that means a client should call ```client.Handler.OnConnected(c)``` manually?

https://github.com/lesismal/arpc/blob/master/client.go#L473

https://github.com/lesismal/arpc/blob/master/README.md#handle-new-connection

**Comment by landbed** [comment]
Well, I got it,  it must be set HandleConnected on the package level.

**Comment by lesismal** [comment]
@landbed 

### 客户端
1. 非主动断开（比如网络错误之类的断开时）：会进行自动重连。因为是客户端是进行持续请求、所以断开时不调用 `OnDisconnected callback` ，因为不应该执行断开清理逻辑而是需要等待重连；重连成功会调用 `OnConnecetd callback` 因为可能需要一些重新初始化工作（比如 [pubsub 重新初始化已订阅的 topic](https://github.com/lesismal/arpc/blob/master/extension/pubsub/client.go#L208)）：
https://github.com/lesismal/arpc/blob/master/client.go#L764

2. 业务层主动断开：需要执行清理等工作，会调用 `OnDisconnected callback`：
https://github.com/lesismal/arpc/blob/master/client.go#L473

### 服务端
断开时，因为服务端是接收请求方，不需要反向进行重连

server、client都持有自己的 Handler，如果先初始化 arpc.DefaultHandler 属性，则后面创建的 server、client 是从它 clone 出来的、也会带有那些属性，但后续设置 server、client 自己的 Handler 属性时不会影响 arpc.DefaultHandler 的属性。

**Comment by lesismal** [comment]
> Well, I got it, it must be set `HandleConnected` on the package level, but the `OnConnected` call is still missing, it should be called before read/recv loop.

您可以在想要看到效果的 client 或 server 端代码中加入 HandleConnected 或者 HandleDisconnected 方法的日志，然后代码里执行断开或者关闭一方进程再观察另一方的日志来查看效果。

**Comment by landbed** [comment]
@lesismal Thanks, I mean ```c.Handler.OnConnected(c)```  must be called manually after we got a new client.

```
arpc.DefaultHandler.HandleConnected(func(c *arpc.Client) {
    doSomethinig(c)
})

client, err := NewClient(...)

client.Handler.OnConnected(client) 
// or
doSomethinig(client)
```

I'm guessing the reason is, this commented line?

https://github.com/lesismal/arpc/blob/master/client.go#L729

or ```c.Handler.OnConnected(c)``` should be called at this line?

https://github.com/lesismal/arpc/blob/master/client.go#L921

**Comment by lesismal** [comment]
> @lesismal Thanks, I mean `c.Handler.OnConnected(c)` must be called manually after we got a new client.
> 
> ```
> arpc.DefaultHandler.HandleConnected(func(c *arpc.Client) {
>     doSomethinig(c)
> })
> 
> client, err := NewClient(...)
> 
> client.Handler.OnConnected(client) 
> // or
> doSomethinig(client)
> ```
> 
> I'm guessing the reason is, this commented line?
> 
> https://github.com/lesismal/arpc/blob/master/client.go#L729
> 
> or `c.Handler.OnConnected(c)` should be called at this line?
> 
> https://github.com/lesismal/arpc/blob/master/client.go#L921

应该在 `NewClient` 之后业务层自己执行，比如：

```golang
func onConnected(c *arpc.Client) {
    ....
)

client, err := NewClient(...) 
onConnected(client)  // step 1: handle it here
client.Handler.OnConnected(onConnected) // step 2: register the handler here
```

之所以没有在创建后自动调用（[注释的这里](https://github.com/lesismal/arpc/blob/master/client.go#L729)），是由于每个 client 可能需要有自己的 Handler 初始化，比如设置中间件：
```golang
client, err := NewClient(...) 
client.Handler.Use(...)
```

我们通常是先 NewClient，然后才能拿到它的 Handler 进行相关的设置。使用 arpc.DefaultHandler 进行设置、然后再 NewClient 也能够达到效果，但是当遇到一个进程中有多个 client 指向多个不同的 server 并且每个 client 需要有不同的 Handler 配置时，使用 arpc.DefaultHandler 会容易产生副作用：
```golang
arpc.DefautHandler.InitForCLient_01(...)
client_01, err := NewClient()

arpc.DefautHandler.InitForCLient_02(...)
client_02, err := NewClient() // client_02 的 Handler 会带有 client_01.Handler 共同的属性，但这属性可能是我们不想要的
```

虽然可以通过重置 arpc.DefaultHandler：
```golang
originHandler := arpc.DefautHandler.Clone()
arpc.DefautHandler.InitForCLient_01(...)
client_01, err := NewClient()

arpc.DefautHandler = originHandler
originHandler = originHandler.Clone()
arpc.DefautHandler.InitForCLient_02(...)
client_02, err := NewClient()

arpc.DefautHandler = originHandler
arpc.DefautHandler.InitForCLient_03(...)
client_03, err := NewClient()
```
但我个人还是觉得相比于 NewClient 之后显示调用 onConnected 更干净、不那么容易引起混乱，毕竟不是所有使用者都会注意到这个细节，就像您来提出这个疑问一样。

**Comment by lesismal** [comment]
@landbed 我在考虑把这个注释取消，允许调用，但是 NewClient 增加个额外的 handler 可选参数，然后多个 client 可以这样：
```golang
handler1 := arpc.NewHandler()
client_01, err := arpc.NewClient(dialer, handler1)

handler2 := arpc.NewHandler()
client_02, err := arpc.NewClient(dialer, handler2)

handler3 := arpc.NewHandler()
client_03, err := arpc.NewClient(dialer, handler3)
```

你觉得这样会不会好些？

**Comment by landbed** [comment]
Thanks!

It's better in my opinion. I really don't like package level magic.

**Comment by lesismal** [comment]
> Thanks!
> 
> It's better in my opinion. I really don't like package level magic.

Done.
Please try v1.1.11.

**Comment by landbed** [comment]
Good job, it works as expected.

**Comment by lesismal** [comment]
> works as ex

Thank you for your feedback!

**Comment by landbed** [comment]
Hi @lesismal 

There is a bug I guess, client.Get/Delete/Set(...) cannot be called in OnDisconnected callback.

c.mux.Lock()
https://github.com/lesismal/arpc/blob/master/client.go#L461

c.mux.Lock()
https://github.com/lesismal/arpc/blob/master/client.go#L72
https://github.com/lesismal/arpc/blob/master/client.go#L86
https://github.com/lesismal/arpc/blob/master/client.go#L98

**Comment by landbed** [comment]
btw, Sorry to post it here, I just think it is related to this issue.

**Comment by lesismal** [comment]
> btw, Sorry to post it here, I just think it is related to this issue.

That's all right.
Fixed: https://github.com/lesismal/arpc/commit/72fae2cffa1665c91950952c3a7bd91dca20355e
Please try the latest.

Thank you for your feedback 😄 ~

**Comment by landbed** [comment]
COOL!
