### ISSUE TITLE
Is there an elegant way to handle multiple client sessions?

### ISSUE THREAD

**Issue by randree** [lesismal/arpc#35]
I would like to work with `arpc` because the benchmark numbers of tests I made are very good. It has a great performance. Fantastic work @lesismal !

In my test environment I have replication of containers with different IP addresses within one network. One container should connect to multiple clients. And if a connection is lost it should start to retry to connect. A simplification of the code would look like:
```golang
...
var clients = make(map[string]*arpc.Client)
...
func connectClients() {
	// find all IP addresses of the the host (e.g. in docker, tasks.foo)
	// Lets say we'll find 10.0.1.3 and 10.0.1.4
	ips, err := net.LookupIP(addrClientLookup) 
	...
	for _, ip := range ips {
		if _, inList := clients[ip.String()]; !inList {
			client, err := arpc.NewClient(func() (net.Conn, error) {
				return net.DialTimeout("tcp", ip.String()+":8888", time.Second*1)
			}, 1)
			if err != nil {
				...
				return
			}
			...
			client.Handler.HandleDisconnected(func(c *arpc.Client) {
				...
				delete(clients, host)
			})
			...
			clients[ip.String()] = client
		}
	}
}
```
`connectClients` is called every second because it can happen that a new container has been added. My issue is if a connection gets lost. In some cases it starts a `Reconnect Trying x`-loop but in other cases it replaces the target IP address from `c.Conn` with one from an other client. Like
```
Map[10.0.1.3][ 10.0.1.3:44108 -> 10.0.1.3:8888 ]
Map[10.0.1.4][ 10.0.1.3:45780 -> 10.0.1.4:8888 ] // correct
```
to somewhat like
```
Map[10.0.1.3][ 10.0.1.3:44108 -> 10.0.1.3:8888 ]
Map[10.0.1.4][ 10.0.1.3:44120 -> 10.0.1.3:8888 ] // wrong
```
without even touching the `HandleDisconnected` handler. `Map[10.0.1.4]` should be deleted because the connection is lost. Anyway is there a better way to handle multiple clients in a way that they don't interfere with each other in a failure situation?

**Comment by lesismal** [comment]
Thank you for your attention and feedback!

I think that's not a problem caused by `arpc`, but just a wrong way to use the same `ip variable` in a `for loop`, try this:
```golang
for _, ip := range ips {
	addr := ip.String()+":8888" // use another variable, to avoid the ip variable changed in next loop
	if _, inList := clients[ip.String()]; !inList {
		client, err := arpc.NewClient(func() (net.Conn, error) {
				return net.DialTimeout("tcp", addr, time.Second*1)
			}, 1)
...
```

**Comment by lesismal** [comment]
btw, when the client is disconnected, it will reconnect automatically, so, usually, you don't need to reconnect yourself. If you want to judge whether it's healthy, just use `client.CheckState()` .

**Comment by lesismal** [comment]
> because the benchmark numbers of tests I made are very good. It has a great performance.

here's other guys benchmark:
https://github.com/micro-svc/go-rpc-framework-benchmark

arpc should be the fastest within the golang community by now... 😄

**Comment by lesismal** [comment]
You are welcome! My pleasure to hear you like it!
