### ISSUE TITLE
为什么需要设计这个maxload?

### ISSUE THREAD

**Issue by trainking** [lesismal/arpc#36]
https://github.com/lesismal/arpc/blob/f60ba57f3a906ef310c4b13d5de101770c9aff19/server.go#L23

为什么需要设计这个maxload？控制数据包的最大数量？并未看到如何修改和初始化这个值？

**Comment by lesismal** [comment]
这个是server可接受的最大连接数配置。默认值为0、不限制连接数量，如果想修改，`server.MaxLoad = numYouWant` 即可。

有的场景是需要考虑限流的，比如直接面向用户的公网用户，避免server连接数量太大导致OOM，会限制连接数上限。即使是内网的服务，有的也需要限制，比如mysql的连接数相关的配置。
