### ISSUE TITLE
处理Notify消息错误

### ISSUE THREAD

**Issue by rwcoding** [lesismal/arpc#37]
https://github.com/lesismal/arpc/blob/f60ba57f3a906ef310c4b13d5de101770c9aff19/handler.go#L630 

cmd  是 notify 的时候，这里会报错，没有rh变量

**Comment by lesismal** [comment]
哦，没有路由的时候好像是要rh为nil，我试下看看

**Comment by rwcoding** [comment]
没有再出现，应该是没有问题了
