### ISSUE TITLE
data race问题

### ISSUE THREAD

**Issue by nickolastone** [lesismal/arpc#38]
简单跑了一下，data race的问题还是很多的，不知是暂时没考虑 还是为了性能故意的race？

像server的
github.com/lesismal/arpc/server.go:127
github.com/lesismal/arpc/server.go:128 
github.com/lesismal/arpc/server.go:42 
github.com/lesismal/arpc/server.go:182 

像client的
github.com/lesismal/arpc/client.go:726 
github.com/lesismal/arpc/client.go:694
github.com/lesismal/arpc/handler.go:595
github.com/lesismal/arpc/handler.go:758 
github.com/lesismal/arpc/client.go:694 

看起来好像不是prod ready的状态？

**Comment by lesismal** [comment]
感谢关注！

这些data race是不影响程序正常运行的。
并发基础设施，经常会涉及data race，如果不影响正常运行、但为了消除data race warning而去加锁，只会浪费性能。
data race只是辅助检查可能存在的风险，并不代表就是真正有问题，如果感兴趣，可以阅读对应的代码来看下。比如：
github.com/lesismal/arpc/handler.go:595

```golang
for i := len(h.msgCoders) - 1; i >= 0; i-- {
	msg = h.msgCoders[i].Decode(c, msg)
}
```

这里的对 h.msgCoders 是读行为，h.msgCoders 是编解码中间件，正确的用法是在 server 初始化阶段、启动监听前就设置好了，后续的并发读行为，虽然会data race，但并不影响程序的正确性。如我前面所说，如果为了消除data race warning告警而加锁，就是浪费性能了。

我的另一个仓库 nbio 里也有人提出过data race的问题，也做过一些解答，可以参考相关 issue:
https://github.com/lesismal/nbio/issues/145
https://github.com/lesismal/nbio/issues/149
更多issue请搜索data race。最近有其他同学来给nbio pr，通过 //go:norace 编译选项消除data race warning，也是个办法，但是arpc目前没有这个计划。

**Comment by lesismal** [comment]
还有一些常见的data race场景比如http router相关的数据结构，也是初始化阶段设置好了、后续的路由查找handler时都是并发读，也是没必要用锁来消除data race warning的。
比如知名的 httprouter:
https://github.com/julienschmidt/httprouter/blob/master/router.go#L466

这里的路由匹配，也都是没有用锁的。我没有实际尝试，你可以试下开启data race选项进行多连接并发压测，应该是也会有data race的吧。

**Comment by nickolastone** [comment]
了解，所以开头第一句就 是否因为性能原因故意的
挺有意思的项目

顺带提个建议，server跟client的内部异常处理模式可能的情况下对齐？当然是我写法有误引起的
例如
server call client 当client没有write 直接return， server的rsp是nil
client call server 当server没有write 直接return， client是wait timeout

此issue应该可以关闭了，感谢

**Comment by lesismal** [comment]
这个先关闭了，继续在这里讨论或者新开个都可以的
