### ISSUE TITLE
您好请问用php语言写rpc的client端有例子吗？

### ISSUE THREAD

**Issue by baoluobao** [lesismal/arpc#39]
n你好，能否提供一个简单的php的client例子，我使用的是你的demo中server和client，用go去实验是可以走得通的，但是换成php去调用go的server就调不通了，请问能否提供一下php的demo呢？下面是我的php代码，用Hprose去实现：

        try {
            $client = \Hprose\Client::create('tcp://localhost:8888', false);
            $res = $client->echo('test');

            var_dump($res);
        } catch (\Exception $e) {
            var_dump($e->getMessage());
        }

报错是："response read error"

server的go代码是：

package main

import (
	"github.com/lesismal/arpc"
	"github.com/json-iterator/go"
)

func main() {
	server := arpc.NewServer()
	server.Codec = jsoniter.ConfigCompatibleWithStandardLibrary

	// register router
	server.Handler.Handle("echo", func(ctx *arpc.Context) {
		str := ""
		if err := ctx.Bind(&str); err == nil {
			ctx.Write("123")
		}
	})

	server.Run("localhost:8888")
}

server端一直报错：Disconnected: invalid body length: 369098752

**Comment by lesismal** [comment]
抱歉，没有支持php的打算。如果有兴趣，欢迎自己实现一个php的，协议格式可以参考readme中的layout。

 \Hprose\Client::create 这个应该是 Hprose 的吧，不是同一个协议没法调用通的。

**Comment by baoluobao** [comment]
好的谢谢
