### ISSUE TITLE
大佬?没有个QQ群或者微信群吗

### ISSUE THREAD

**Issue by fyyang** [lesismal/arpc#4]

**Comment by lesismal** [comment]
社交太费精力、还得养家 :joy::joy: ， 常规的问题 github issue 足够了

**Comment by fyyang** [comment]
关键是你这两周破坏性改动有点大, 所以我以为会有相关交流群, 我也可以帮你维护维护

**Comment by lesismal** [comment]
> 关键是你这两周破坏性改动有点大, 所以我以为会有相关交流群, 我也可以帮你维护维护

除了目录结构中间变动了导致之前的子包import 路径变化，其他主要的接口这些应该还是兼容的。

维护开 issue 就可以了，欢迎常来issue pr  :smile:

**Comment by lesismal** [comment]
昨天提交了一波也主要是Client、Context一些内存布局优化，Context有一些中间版本的功能，为了支持多次ctx.Write，后来想想，实际场景没什么必要ctx.Write多次，就给去掉了，但是为它增加的变量竟然忘记删了，然后一个Context size大于一个cache line，尴尬。。。

**Comment by lesismal** [comment]
中间还考虑过使用sync.Pool，但是出于以下几个原因也没有使用：

1. go 1.8 以后的 gc 已经比较好了，常规业务场景使用 sync.Pool 效果也未必明显
2. 一个连接一个 Client ，数量不大，不太需要使用
3. Context 由于支持异步回包，生命周期结束的时间点难以确定，如果使用 sync.Pool 进行管理，需要提供额外的方法比如 Retain/Release ，增加应用层心智负担
4. rpcSession 在使用流程中比较复杂，网络状况ok的情况下 rpcSession通常由Client作为发起方调用Call的过程中持有，数量也不至于巨大
5. Message 通常是内存使用最多的，早期有考虑使用 sync.Pool 进行内存 Message 的内存管理，但是为了更灵活方便的功能支持放弃了，大致原因如下：

> 1）ARPC 的消息发送不像其他一些 RPC 框架那样直接调用 Conn.Write、而是单独的发送协程进行异步写，直接调用 Conn.Write 的方式在高并发调用时 Mutex 竞争、排队发送、性能更差，ARPC 异步写并且支持批次写、效率更高

> 2）ARPC 支持广播，广播包无法在一个 Conn 写完 Message 时放回 sync.Pool ，而需要所有广播对象都写完或者失败时才能放回，这就需要额外增加引用计数、广播消息类型区分、按类型区分是否使用 sync.Pool 等一种或几种机制

> 3）ARPC 支持编码中间件，给应用层预留了更自由的 Message 编解码处理，比如增加压缩、链路追踪或者其他附加数据，如果使用 sync.Pool ，应用层在进行编码中间件扩展时也会有更大的心智负担

> 以上几种，也都需要增加额外的代码复杂度，在常规业务场景下，新增的代码性能消耗损失可能会大于使用 sync.Pool 带来的利益

**Comment by lesismal** [comment]
早期的 Message 定义也是直接  type Message []byte 的，后来为了方便应用层扩展而支持了编码中间件、Context信息传递。这些细节比较让人纠结，咬文嚼字的 :joy: :joy:

**Comment by fyyang** [comment]
可以, 我也算是go新手, 深入一点的东西没有特别详细的了解. 目前仅限于用.

**Comment by lesismal** [comment]
> 可以, 我也算是go新手, 深入一点的东西没有特别详细的了解. 目前仅限于用.

好的，如果有什么需要的feature都可以提出来，咱们看看是否适合加入支持

**Comment by fyyang** [comment]
目前只有Pub/Sub支持密码, 其他正常的rpc链接验证是否也可以写个支持一下, 包括websocket

**Comment by lesismal** [comment]
> 目前只有Pub/Sub支持密码, 其他正常的rpc链接验证是否也可以写个支持一下, 包括websocket

框架层次明确更好些，比如http、grpc之类的应该也只是提供框架、不提供认证之类的业务层功能
而且验证比较简单，通常留给业务层就可以了，比如你的server.Handler.Handle("auth", ...)，类似pubsub包里server的验证方式 [auth](https://github.com/lesismal/arpc/blob/master/extension/pubsub/server.go#L284)

websocket就更简单了，你可以自己传入一个upgrader并自己定制CheckOrigin，比如:

```golang
import "github.com/lesismal/arpc/extension/protocol/websocket"

upgrader := &websocket.Upgrader{
	CheckOrigin: func(r *http.Request) bool {
		if xxx {
			return false
		}
		return true
	},
}
listener, err := websocket.Listen(addr, upgrader)
```
