### ISSUE TITLE
Could you update readme slack link?

### ISSUE THREAD

**Issue by Kabochar** [lesismal/arpc#40]
你好，lesismal。项目 readme 上的 slack 链接过期了，能否更新下？

按照 300 多天前的要求，如果要沟通arpc，沟通项目还是倾向使用 issue 进行提问吗？
https://www.v2ex.com/t/794435

**Comment by lesismal** [comment]
Hi, 感谢关注！

一般问题 issue 更好，也方便其他人有类似的问题时直接查阅。
有想更多了解交流的slack更方便些，免费版的slack频道好像只能通过邀请的方式加入，邀请连接是一个月有效期，最新的：
https://join.slack.com/t/arpcnbio/shared_invite/zt-1esuz619h-SbKacrYHNdbkNmO9SV~X1A

欢迎来聊，:smile:

**Comment by Kabochar** [comment]
get，已加入😀

**Comment by Kabochar** [comment]
好吧，群里好像有点安静(众多大咖)。这里还是使用 issue 进行提问吧。

想问下 lesismal，关于 arpc 有对应架构设计图吗？这样子总览方便按模块进行学习。

或者推荐下学习 arpc 的方式？(虽然除去example目录，实际代码并不多)。

补贴一个早些时候你在 v2ex 介绍 aprc 的帖子
https://www.v2ex.com/t/734682

**Comment by lesismal** [comment]
> 好吧，群里好像有点安静(众多大咖)。这里还是使用 issue 进行提问吧。
> 
> 想问下 lesismal，关于 arpc 有对应架构设计图吗？这样子总览方便按模块进行学习。
> 
> 或者推荐下学习 arpc 的方式？(虽然除去example目录，实际代码并不多)。
> 
> 补贴一个早些时候你在 v2ex 介绍 aprc 的帖子 https://www.v2ex.com/t/734682

与其他rpc框架相比，arpc支持的功能、扩展能力甚至更强，但是实现的代码比它们简单得多，如果使用的基础上想进一步看下实现、直接读源码就好了

**Comment by lesismal** [comment]
源码不多，估计随便花个把小时就能把源码主体看个差不多了，想细看就再精读一下

**Comment by Kabochar** [comment]
好，谢谢 lesismal 回复。回头好好研读下。

**Comment by lesismal** [comment]
> 好，谢谢 lesismal 回复。回头好好研读下。

好的。

最快的方式，就启动个server或者client，调用栈、单步调试看下代码流程就大概清楚了。主要就网络、编解码，中间件之类的都是属于流程中的一些扩展步骤，没什么复杂度，有需要解释的地方继续来提问就好了

**Comment by Kabochar** [comment]
好的 😋
