### ISSUE TITLE
请问server和client端是如何管理tcp连接的？需要业务层自己做连接池对连接进行复用吗？

### ISSUE THREAD

**Issue by OLPMO** [lesismal/arpc#42]

**Comment by lesismal** [comment]
两点之间，单个连接的性能其实是足够的，如果确实量很大或者是多个server节点想做负载均衡，可以用pool。
已经自带了个简单的Pool实现：
https://github.com/lesismal/arpc/blob/master/client.go#L952

例子：
https://github.com/lesismal/arpc/blob/master/examples/pool/client/client.go

如果是到多个server节点，dialer的地方自己连接到不通的节点就可以了：
https://github.com/lesismal/arpc/blob/master/examples/pool/client/client.go#L13

自己实现个pool也比较容易，可以根据你们实际需要来做

如果需要服务发现，这里有个简单的例子可供参考：
https://github.com/lesismal/arpc/tree/master/examples/micro/etcd

服务发现本身是个简单的事情、主要就是配置注册与发现以及连接管理，用户根据自家业务来实现就可以了，arpc只提供基础设施

另外，不只是支持tcp，实现了net.Conn就都可以作为arpc的网络载体，比如unix socket, tls, websocket, kcp, quic, utp，这里有使用这些协议的例子：
https://github.com/lesismal/arpc/tree/master/examples/protocols
