### ISSUE TITLE
怎么添加和获取message.values

### ISSUE THREAD

**Issue by wksw** [lesismal/arpc#43]
#### client.go
```golang
err = client.Call("/echo/sync", &req, &rsp, time.Second*5, map[interface{}]interface{}{
		"x-arpc-context": "xxxxx",
	})
```

#### server.go
```golang
fmt.Printf("message values: %+v", ctx.Message.Values())
```
这种方式获取不到message.values

**Comment by lesismal** [comment]
这主要是为用户留出扩展空间的，用户可以自己定义编解码中间件，比如tracing的中间件扩展和示例：
https://github.com/lesismal/arpc/tree/master/examples/middleware/coder/tracing

因为对于arpc本身，用户的value的格式未知，所以arpc自己难做这种内置的定制，具体的实现应由用户完成。

中间件的好处是业务逻辑解耦，但消耗多一点性能。

如果不想定制编解码中间件，最简单的方式就是在业务需要的地方把这些value带在Call的结构体上

**Comment by wksw** [comment]
https://github.com/lesismal/arpc/blob/master/extension/middleware/coder/msgpack/msgpack.go

**Comment by fengqi** [comment]
使用 msgpack 这个 中间件可以实现 values 的传递，但是等于是在内置的 jsoncodec 编码过一次的基础上再次编码一次

如果newMessage 里 ValueToBytes 这一步把 values 也传入，默认的实现可以不处理 values，但是自定义的就可以处理，这样起码不用再coder里再去编码一次

只需要把 Codec 这个接口的 Marshal和Unmarshal加个参数，或者新开两个 withValues方法，加上noop默认无实现，是不是也可以做的向下兼容

**Comment by fengqi** [comment]
> 使用 msgpack 这个 中间件可以实现 values 的传递，但是等于是在内置的 jsoncodec 编码过一次的基础上再次编码一次
> 
> 如果newMessage 里 ValueToBytes 这一步把 values 也传入，默认的实现可以不处理 values，但是自定义的就可以处理，这样起码不用再coder里再去编码一次
> 
> 只需要把 Codec 这个接口的 Marshal和Unmarshal加个参数，或者新开两个 withValues方法，加上noop默认无实现，是不是也可以做的向下兼容

好行不太行，应该values多出来的bodyLen传不出来，额 那现在的value和body分开处理局限有点大啊

**Comment by lesismal** [comment]
> 好行不太行，应该values多出来的bodyLen传不出来，额 那现在的value和body分开处理局限有点大啊

所以我给的建议是上面提到的tracing中间件的例子，可以参考这个例子用二进制来做。实际上把你需要的值打包到msg、追加到包体尾部或者取出解析的逻辑的编解码中间件已经封装好了：
https://github.com/lesismal/arpc/blob/5d0e0e9b1b7ed540a64efbeaea1fa5b0e53f99fa/extension/middleware/coder/appender.go

你只需要实现ValueToBytes BytesToValue方法作为Appender的参数，然后创建Appender：
https://github.com/lesismal/arpc/blob/master/extension/middleware/coder/tracing/tracer.go#L85

并使用它作为编解码中间件就可以了（这里的Tracer是切面形式的has a Appender，Appender实现了Encode/Decode）：
https://github.com/lesismal/arpc/blob/master/examples/middleware/coder/tracing/server/server.go#L41

**Comment by lesismal** [comment]
消息头的第 HeaderIndexFlag index 字节是保留字节，主要是留给用户自行扩展时做标记位用的，注意，如果你使用了多个中间件都需要设置标记位，不要使用相同的标记位index，免得冲突了。如果编解码中间件都是自己团队的功能，通常就一个标记位、都在一个编解码中间件中实现功能性价比最高。保留字节在这里：
https://github.com/lesismal/arpc/blob/master/proto.go#L197

**Comment by lesismal** [comment]
http因为自带了header的编解码，所以用户添加header就可以、不需要自己操心编解码。而rpc为了性能是固定定义的pb之类的，如果是非固定定义比如json格式，那你只需要把tracing相关的字段作为json公共的字段就可以了，比如用map，或者你们的json结构体都继承/has a/切面一个tracing相关的结构体，这种就不需要编解码中间件了，性价比也是最高的。

当然，即使用pb，也可以所有结构体都has a公共的tracign字段，但这是业务侵入的，可能涉及旧业务、兼容之类的问题，要看你们自己的取舍了。
