### ISSUE TITLE
可以类似http那种增加header信息吗？

### ISSUE THREAD

**Issue by fengqi** [lesismal/arpc#44]
我现在有个场景，比如做链路跟踪的时候，需要把当前环境的traceID和spanID传到下游

这种数据更适合在middleware内部去实现，而不用干扰到业务代码

**Comment by lesismal** [comment]
可以使用中间件实现，这里有一个使用 `opentracing` 的中间件/扩展的例子，你们可以参考这个实现、根据自己需要来定制：
https://github.com/lesismal/arpc/tree/master/examples/middleware/coder/tracing

**Comment by lesismal** [comment]
例子大概就是 client.Call 携带 tracing 相关信息，arpc server 收到请求后拿到 tracing 信息、再请求下游的 http 服务（或者其他服务）时带上这个需要的信息

**Comment by fengqi** [comment]
好的，我先试试看

**Comment by fengqi** [comment]
我看了下，其实就是各个环节手动的把需要的信息往values写入或者读取吗？

**Comment by lesismal** [comment]
> 我看了下，其实就是各个环节手动的把需要的信息往values写入或者读取吗？

对。http的是带到header里编解码是一个道理
