### ISSUE TITLE
Client supports pipeline?

### ISSUE THREAD

**Issue by duchiporexia** [lesismal/arpc#5]
Currently, for the req/res mode, the client is blocked when the response has not yet come back. Hence, the whole connection is blocked.

Does it support the feature like fasthttp.**PipelineClient**, which can send multiple requests once?  In this way, multiple go routine could share one client connection.

**Comment by lesismal** [comment]
although writev is rarely triggered by the normal sending frequency, the default setting is still that when there are multiple packets in the sending queue, the packets will be sent in batches by writev to reduce system calls, see [here](https://github.com/lesismal/arpc/blob/master/client.go#L680). performance is sufficient, and many server's and client's async-styles are supported so there is no need to expose the pipeline-like interface

**Comment by duchiporexia** [comment]
Thanks. It seems that it's already a pipeline client because the client can be reused before the previous response is returned.

**Comment by lesismal** [comment]
> Thanks. It seems that it's already a pipeline client because the client can be reused before the previous response is returned.

yes it is, wish u like it ~ :smile::smile::smile:
