### ISSUE TITLE
can routes be added dynamically?

### ISSUE THREAD

**Issue by UallenQbit** [lesismal/arpc#66]
can routes be added dynamically?

**Comment by lesismal** [comment]
Thank you for your attention and feedback to arpc!

arpc.Handler is a interface{}, the default implementation(arpc.handler) doesn't support concurrent add operations.
But you can implement a Handler yourself and set it: arpc.Client/Server.Handler = yourHandler. The easiest way to implement it is copy the arpc/handler.go and add mutex operations in the handle/HandleStream/OnMessage funcs:
https://github.com/lesismal/arpc/blob/master/handler.go#L572
https://github.com/lesismal/arpc/blob/master/handler.go#L701

**Comment by lesismal** [comment]
Welcome to try arpc!

Here's aother easier way:
```golang
newHandler := server.Handler.Clone()
newHandler.Handle(...) // or other logic you want
server.handler = newHandler
```
