### ISSUE TITLE
大佬，请教下用arpc在两台服务器之间同步数据

### ISSUE THREAD

**Issue by ericjing83** [lesismal/arpc#68]
您好，大佬，

请教下，如果用这个arpc库，让master服务器实时同步数据给slave服务器，相当于arpc完全工作在云端后台，一个client端（数据中心的slave服务器）对应1个服务端（同一个数据中心的master服务器），代码应该如何写啊，我看了example里面有很多高级功能，有点晕了。
我主要想知道，在数据中心的内网里，master和slave如何通过arpc通信。这样单个连接TPS3~5W没问题吧？

**Comment by lesismal** [comment]
client 连接到 server 上， server 把需要同步的数据指定的 Method/Route 通过 client.Notify 给对方 就可以了。例如：
https://github.com/lesismal/arpc/blob/master/examples/notify/server/server.go
如果需要认证之类的步骤，可以client连接成功后先Call调用个认证的、server只对认证通过的client进行 Notify
如果只是简单发布订阅，也可以参考发布订阅的例子（但这个发布订阅实现只是做例子、比较简单、也对性能略损失一点点，没太大必要）：
https://github.com/lesismal/arpc/tree/master/examples/pubsub

如果你的数据需要持久化、确保master slave之间的一致性， 则需要自己根据 master slave 之间的数据状态做额外的一些处理，例如server slave之间断线重连之类的

数据中心内网的话，网络通常比较好，那么单个连接的tps，主要取决于你的硬件配置、包体size之类的，3-5w这个量级不算很大、应该没太大压力，但请以你们实际硬件环境测试为准
