### ISSUE TITLE
大佬你好，请教下在fiber里怎么集成arpc做webchat

### ISSUE THREAD

**Issue by hiifong** [lesismal/arpc#69]

**Comment by lesismal** [comment]
感谢关注!

刚提交了下, 增加了fiber的转换, 可以参考下这里:
https://github.com/lesismal/arpc/blob/master/examples/protocols/websocket/server/server.go

这里的 "/ws" 路由用于 arpc 的 method/router, 如果fiber还有其他websocket, 可以自己设定不同的路由

client代码在同级目录下, arpc go和js都有:
https://github.com/lesismal/arpc/tree/master/examples/protocols/websocket
client dialer的路由需要与server的路由相同:
https://github.com/lesismal/arpc/blob/master/examples/protocols/websocket/client/client.go#L20
https://github.com/lesismal/arpc/blob/master/examples/protocols/websocket/jsclient/hello.html#L11
